language: python
sudo: false
python:
  - "2.7"
virtualenv:
    system_site_packages: true
env:
  global:
    - secure: "L2ja+ZnV83w4qG3E8FwTjm0D6IWNOnj5wuFOjYTwbzQP4OAgLAWBzCMtxzWy5sMxFLtRgkswBH1d5f5kg8Ab7GIyAMFgQwe8UFqMJ+N05QNszE1mJkAvJtv2XN7669XXQhTt5EXfHrCcGZaODVnI2CEA8GB5DxiHO2Lcqf/xvgE="
    - secure: "P+DYgkeMFvXMYzfZoE2J9cILdI78vVL9YGSkGYMXADC77b0fOrpnovuS7QyWUxOQ54FfNaA0AgrUS5epzCQ1JVYrJFvljBtxZJTZs3yn4rGrIz1s2P8gjbNZkJzEG6+T8lS5LQQRNc5akI+BgaNC0zqTcsk58S3P5ZbmXs6q0q9vMS8cHMCsl+gmzWpmiqL7DjP8t8lOlxQ0mDPUUkp6uvlYfM/iIC+ReQK7YVD8tXxBlAE64p97Hc387btYU1eIcYAFL+3x/9BfV5FXQZoGn4xKOFjz/U6fGzVEtRnLe1CE+5tCxUVLxXB1F0sWRs+YGwB6R1hQIuz+Yp3o5uey7HN8HJEvB3//Jp99RimFeCLpRI+0wdJfp6ykImUHdeLyCWAkZ21eJmu1H2CH6agcLtZiJfiyi4Pi2En642aJQyowuIubB5G5HJusPDIkkU3J8p8zGif3pgO8U+7F3fze8deN8+mV/xsT5DInYW3yLREvzsFMpTcx5vCDiTFM/bX7uxMuTse6qXFuG8twsrqs4jGby7LPxDbUDV96KMp+u3IMqGgXX1x8hPoWpOnDL0ampYYLQczpSZkAhQwTgInZIMneFxQZba9PjEoKr6SRGM4kf8IsJ8SXcn2u45lMHeZT04BadZycuWASEzqDnEd4XMoAdcItA8w/FyS0HqT6nOs="
addons:
  apt:
    packages:
    - git

before_install: 
  - chmod +x before_install.sh
  - . ./before_install.sh
  - chmod +x color_define.sh
  - . ./color_define.sh

install: 
  - chmod +x install.sh
  - . ./install.sh
  - chmod +x version_summary.sh
  - . ./version_summary.sh
  - chmod +x run.sh

script: 
  - ./run.sh eg1 no
  - ./run.sh eg3 no
  - ./run.sh eg5 no
  - ./run.sh eg6 no
  - ./run.sh eg7 no
  - ./run.sh NC no
  - ./run.sh MCH  yes
  - ./run.sh solvent_hexane no
  - ./run.sh methane no

after_script:
  - chmod +x after_install.sh
  - . ./after_install.sh
  
cache:
  pip: true
  apt: true
  # directories:
  #   - $HOME/anaconda/pkgs

branches:
  only:
    - /^rmgpy-.*$/
    - /^rmgdb-.*$/
    - /^rmgpydb-.*$/